name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shared:
    uses: mitlibraries/.github/.github/workflows/ruby-shared-ci.yml@3d2816ffa487f3e99b650103252e44552d277ef6 # main
