name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shared:
    uses: mitlibraries/.github/.github/workflows/ruby-shared-ci.yml@ce22f68a1726bdacfa10393aeac0763346bdd4a3 # main
