name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shared:
    uses: mitlibraries/.github/.github/workflows/ruby-shared-ci.yml@935e2fa59553dbb29b68d3c186a041f3233bfd10 # main
